In [3]:
from django.db.models.signals import pre_delete
from numpy import number
from selenium.webdriver.support.expected_conditions import element_selection_state_to_be
from setuptools.command.build_ext import if_dl
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pc-6\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.2)
Collecting python-dateutil>=2.8.2 (from pandas)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: tzdata in c:\users\pc-6\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pc-6\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.9 MB 4.2 MB/s eta 0:00:03
   ------------- -------------------------- 3.4/9.9 MB 6.9 MB/s eta 0:00:01
   ------------- -------------------------- 3.4/9.9 MB 6.9 MB/s eta 0:00:01
   ---------------- ----------------------- 4.2/9.9 MB 4.7 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.9 MB 4.9 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/9.9 MB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 8.7/9.9 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 5.8 MB/s  0:00:02
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Installing collected packages: python-dateutil, pandas

   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.1 python-dateutil-2.9.0.post0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import pandas as pd

hr = pd.read_excel('HR_Dataset_for_PowerBI_with_Errors.xlsx')
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [18]:
hr.isnull().sum()

Employee ID         6
Department          6
Hire Date           5
Current Position    7
Salary (USD)        1
Last Raise Date     7
Position Changed    6
New Position        6
dtype: int64

In [21]:

hr.loc[0: 99, 'Employee ID'] = ['E' + str(i).zfill(4)
                                for i in range(1, 101)]
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [22]:
hr.isnull().sum()

Employee ID         0
Department          6
Hire Date           5
Current Position    7
Salary (USD)        1
Last Raise Date     7
Position Changed    6
New Position        6
dtype: int64

In [24]:
hr['Department'] = hr['Department'].fillna('Data Analyst')
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [42]:
# hr['Hire Date'] = hr['Hire Date'].fillna(hr['Hire Date'].mean()).dt.date

hr['Hire Date'] = pd.to_datetime(hr['Hire Date'])
hr['Hire Date'] = hr['Hire Date'].interpolate()
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880,2018-09-27,No,Lead

In [28]:
hr.loc[14,'Current Position'] = 'Mid'
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [32]:
hr.loc[[16,23,28], 'Current Position'] = ['Mid', 'Senior', 'Junior']
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [31]:
hr.loc[[40,66,79,81], 'Current Position'] = ['Manager', 'Lead', 'Junior', 'Mid']
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [40]:
hr.loc[83,'Salary (USD)'] = 2000

hr.loc[hr['Salary (USD)'] < 0, 'Salary (USD)'] = hr['Salary (USD)'].abs()
hr['Salary (USD)'] = hr['Salary (USD)'].round()
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880,2018-09-27,No,Lead

In [41]:

hr['Last Raise Date'] = pd.to_datetime(hr['Last Raise Date'])
hr['Last Raise Date'] = hr['Last Raise Date'].interpolate()
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880,2018-09-27,No,Lead