In [10]:
import pandas as pd

print(pd.__version__)

2.3.3

In [2]:
# 1. DataFrame va Series asosida ishlash
# CSV faylni pd.read_csv() orqali o‘qib oling.
# Price ustunini Series sifatida ajratib oling va eng katta narxni toping.
# Faqat Food va Price ustunlarini ajratib yangi DataFrame yarating.

import pandas as pd

polo = pd.read_csv('foods.csv')
polo

         Food   Category  Price  Quantity      Place  Customer  Rating
0      Shorva  Fast Food  11069         1    Andijon  Gulbahor       2
1         Non  Fast Food  36845         2       Xiva  Gulbahor       5
2    Shashlik  Fast Food  42216         4   Toshkent     Hasan       4
3    Shashlik     Milliy  48152         1   Toshkent    Malika       2
4         Non   Ichimlik  42391         5   Namangan  Gulbahor       4
5      Shorva   Ichimlik  15967         3   Toshkent     Hasan       5
6        Qazi   Ichimlik  26865         4       Xiva     Aziza       2
7         Non  Fast Food  21831         1       Xiva  Gulbahor       2
8       Somsa     Milliy  21292         3  Samarqand     Husan       3
9         Osh  Fast Food  20956         1  Samarqand     Hasan       2
10       Qazi  Fast Food  20607         3   Farg'ona   Dilshod       5
11       Qazi   Ichimlik  28505         5  Samarqand   Dilshod       3
12        Non  Shirinlik  36491         3       Xiva       Ali       2
13   Shashlik     Milliy  27625         5   Toshkent    Malika       2
14    Lag'mon  Shirinlik  19228         2   Namangan   Dilshod       1
15    Lag'mon   Ichimlik  44653         1       Xiva     Husan       5
16       Qazi   Ichimlik  32019         1       Xiva       Ali       3
17     Shorva   Ichimlik  42035         5   Namangan    Malika       2
18        Osh  Shirinlik   8233         4     Buxoro     Husan       2
19        Osh     Milliy  37442         4   Namangan      Vali       5
20  Chuchvara   Ichimlik  35198         3     Buxoro      Vali       5
21      Somsa  Fast Food  46657         2     Buxoro  Gulbahor       5
22       Choy   Ichimlik  43044         2  Samarqand     Hasan       3
23        Non   Ichimlik  46761         1     Buxoro    Malika       5
24      Somsa     Milliy  18655         5   Namangan    Malika       3
25       Choy     Milliy  31928         1     Buxoro    Malika       2
26       Qazi  Shirinlik  25370         3  Samarqand  Gulbahor       5
27        Non  Shirinlik   8936         1     Buxoro     Hasan       4
28     Shorva   Ichimlik  44066         1   Farg'ona  Gulbahor       1
29     Shorva     Milliy  20172         3   Toshkent  Gulbahor       2
30        Non  Shirinlik  14811         5   Namangan     Husan       4
31    Lag'mon   Ichimlik  26960         3   Farg'ona      Vali       1
32      Manti  Shirinlik  32983         1  Samarqand     Aziza       4
33      Manti  Fast Food  14603         2       Xiva      Vali       3
34   Shashlik   Ichimlik  16477         5   Toshkent    Malika       5
35        Non  Shirinlik  18652         4   Toshkent    Malika       1
36   Shashlik  Shirinlik  49943         4   Farg'ona     Aziza       3
37      Manti   Ichimlik  19089         3   Namangan  Gulbahor       2
38       Qazi   Ichimlik  37581         4    Andijon  Gulbahor       3
39      Manti  Fast Food  22404         5  Samarqand       Ali       1
40        Osh  Fast Food  20733         4  Samarqand     Hasan       3
41     Shorva   Ichimlik  38943         2     Buxoro   Dilshod       3
42       Qazi     Milliy  35873         5   Farg'ona     Hasan       5
43        Osh   Ichimlik  19619         4   Toshkent   Dilshod       4
44     Shorva  Shirinlik  14988         3       Xiva    Malika       1
45   Shashlik     Milliy  22808         3  Samarqand     Husan       3
46      Somsa   Ichimlik  32205         1   Namangan   Dilshod       3
47       Qazi     Milliy  17214         5     Buxoro      Vali       1
48      Somsa  Shirinlik  25418         4   Namangan     Hasan       3
49      Somsa  Fast Food  16773         4   Toshkent      Vali       3

In [3]:
narx = polo.query('Price == Price.max()')
narx

        Food   Category  Price  Quantity     Place Customer  Rating
36  Shashlik  Shirinlik  49943         4  Farg'ona    Aziza       3

In [17]:
dataframe = polo [['Food', 'Price']]
dataframe

         Food  Price
0      Shorva  11069
1         Non  36845
2    Shashlik  42216
3    Shashlik  48152
4         Non  42391
5      Shorva  15967
6        Qazi  26865
7         Non  21831
8       Somsa  21292
9         Osh  20956
10       Qazi  20607
11       Qazi  28505
12        Non  36491
13   Shashlik  27625
14    Lag'mon  19228
15    Lag'mon  44653
16       Qazi  32019
17     Shorva  42035
18        Osh   8233
19        Osh  37442
20  Chuchvara  35198
21      Somsa  46657
22       Choy  43044
23        Non  46761
24      Somsa  18655
25       Choy  31928
26       Qazi  25370
27        Non   8936
28     Shorva  44066
29     Shorva  20172
30        Non  14811
31    Lag'mon  26960
32      Manti  32983
33      Manti  14603
34   Shashlik  16477
35        Non  18652
36   Shashlik  49943
37      Manti  19089
38       Qazi  37581
39      Manti  22404
40        Osh  20733
41     Shorva  38943
42       Qazi  35873
43        Osh  19619
44     Shorva  14988
45   Shashlik  22808
46      Somsa  32205
47       Qazi  17214
48      Somsa  25418
49      Somsa  16773

In [15]:
# 2. Filterlash va shartli tanlash
# Narxi 30000 so‘mdan yuqori bo‘lgan taomlarni chiqaring.

filtered = polo.query('Price > 30000')
filtered

         Food   Category  Price  Quantity      Place  Customer  Rating
1         Non  Fast Food  36845         2       Xiva  Gulbahor       5
2    Shashlik  Fast Food  42216         4   Toshkent     Hasan       4
3    Shashlik     Milliy  48152         1   Toshkent    Malika       2
4         Non   Ichimlik  42391         5   Namangan  Gulbahor       4
12        Non  Shirinlik  36491         3       Xiva       Ali       2
15    Lag'mon   Ichimlik  44653         1       Xiva     Husan       5
16       Qazi   Ichimlik  32019         1       Xiva       Ali       3
17     Shorva   Ichimlik  42035         5   Namangan    Malika       2
19        Osh     Milliy  37442         4   Namangan      Vali       5
20  Chuchvara   Ichimlik  35198         3     Buxoro      Vali       5
21      Somsa  Fast Food  46657         2     Buxoro  Gulbahor       5
22       Choy   Ichimlik  43044         2  Samarqand     Hasan       3
23        Non   Ichimlik  46761         1     Buxoro    Malika       5
25       Choy     Milliy  31928         1     Buxoro    Malika       2
28     Shorva   Ichimlik  44066         1   Farg'ona  Gulbahor       1
32      Manti  Shirinlik  32983         1  Samarqand     Aziza       4
36   Shashlik  Shirinlik  49943         4   Farg'ona     Aziza       3
38       Qazi   Ichimlik  37581         4    Andijon  Gulbahor       3
41     Shorva   Ichimlik  38943         2     Buxoro   Dilshod       3
42       Qazi     Milliy  35873         5   Farg'ona     Hasan       5
46      Somsa   Ichimlik  32205         1   Namangan   Dilshod       3

In [22]:
# Rating 4 va undan yuqori bo‘lgan mijozlar ro‘yxatini ajrating
filtered = polo.query('Rating >= 4')
filtered

         Food   Category  Price  Quantity      Place  Customer  Rating
1         Non  Fast Food  36845         2       Xiva  Gulbahor       5
2    Shashlik  Fast Food  42216         4   Toshkent     Hasan       4
4         Non   Ichimlik  42391         5   Namangan  Gulbahor       4
5      Shorva   Ichimlik  15967         3   Toshkent     Hasan       5
10       Qazi  Fast Food  20607         3   Farg'ona   Dilshod       5
15    Lag'mon   Ichimlik  44653         1       Xiva     Husan       5
19        Osh     Milliy  37442         4   Namangan      Vali       5
20  Chuchvara   Ichimlik  35198         3     Buxoro      Vali       5
21      Somsa  Fast Food  46657         2     Buxoro  Gulbahor       5
23        Non   Ichimlik  46761         1     Buxoro    Malika       5
26       Qazi  Shirinlik  25370         3  Samarqand  Gulbahor       5
27        Non  Shirinlik   8936         1     Buxoro     Hasan       4
30        Non  Shirinlik  14811         5   Namangan     Husan       4
32      Manti  Shirinlik  32983         1  Samarqand     Aziza       4
34   Shashlik   Ichimlik  16477         5   Toshkent    Malika       5
42       Qazi     Milliy  35873         5   Farg'ona     Hasan       5
43        Osh   Ichimlik  19619         4   Toshkent   Dilshod       4

In [20]:
# Place = "Toshkent" bo‘lgan barcha buyurtmalarni alohida ko‘rsating.
filtered = polo.query('Place == "Toshkent"')
filtered

        Food   Category  Price  Quantity     Place  Customer  Rating
2   Shashlik  Fast Food  42216         4  Toshkent     Hasan       4
3   Shashlik     Milliy  48152         1  Toshkent    Malika       2
5     Shorva   Ichimlik  15967         3  Toshkent     Hasan       5
13  Shashlik     Milliy  27625         5  Toshkent    Malika       2
29    Shorva     Milliy  20172         3  Toshkent  Gulbahor       2
34  Shashlik   Ichimlik  16477         5  Toshkent    Malika       5
35       Non  Shirinlik  18652         4  Toshkent    Malika       1
43       Osh   Ichimlik  19619         4  Toshkent   Dilshod       4
49     Somsa  Fast Food  16773         4  Toshkent      Vali       3

In [20]:
# 3. GroupBy bilan ishlash
# Category bo‘yicha o‘rtacha narxni hisoblang.

polo = pd.read_csv('foods.csv')
category = polo.groupby('Category')['Price'].mean()
category

Category
Fast Food    24972.181818
Ichimlik     32909.888889
Milliy       28116.100000
Shirinlik    23186.636364
Name: Price, dtype: float64

In [36]:
# Place bo‘yicha jami buyurtma sonini toping.
polo = polo.groupby('Place')['Quantity'].count()

Place
Andijon      2
Buxoro       8
Farg'ona     5
Namangan     9
Samarqand    9
Toshkent     9
Xiva         8
Name: Quantity, dtype: int64

In [27]:
# Har bir Customer bo‘yicha sarflagan umumiy summani (Price * Quantity) hisoblang
polo['umumiy_summa'] = polo['Price'] * polo['Quantity']
polo.groupby('Customer')['umumiy_summa'].sum()

Customer
Ali         253512
Aziza       340215
Dilshod     431369
Gulbahor    800142
Hasan       696714
Husan       283940
Malika      770373
Vali        518610
Name: umumiy_summa, dtype: int64

In [31]:
# 4. Pivot Table
# Place va Category bo‘yicha pivot jadval tuzing, unda qiymat sifatida Quantity yig‘indisi chiqsin.

pivot = pd.pivot_table(polo, values = 'Quantity', index = 'Place', columns = 'Category',
                       aggfunc = 'sum')
pivot

Category   Fast Food  Ichimlik  Milliy  Shirinlik
Place
Andijon          1.0       4.0     NaN        NaN
Buxoro           2.0       6.0     6.0        5.0
Farg'ona         3.0       4.0     5.0        4.0
Namangan         NaN      14.0     9.0       11.0
Samarqand       10.0       7.0     6.0        4.0
Toshkent         8.0      12.0     9.0        4.0
Xiva             5.0       6.0     NaN        6.0

In [35]:
# Customer va Food bo‘yicha pivot_table tuzing va o‘rtacha Ratingni ko‘rsating.
pivot = pd.pivot_table(polo, values = 'Rating', index = 'Customer', columns = 'Food',
                       aggfunc = 'mean')
pivot

Food,Choy,Chuchvara,Lag'mon,Manti,Non,Osh,Qazi,Shashlik,Shorva,Somsa
Customer,,,,,,,,,,
Ali,NaN,NaN,NaN,1.0,2.000000,NaN,3.0,NaN,NaN,NaN
Aziza,NaN,NaN,NaN,4.0,NaN,NaN,2.0,3.0,NaN,NaN
Dilshod,NaN,NaN,1.0,NaN,NaN,4.0,4.0,NaN,3.000000,3.0
Gulbahor,NaN,NaN,NaN,2.0,3.666667,NaN,4.0,NaN,1.666667,5.0
Hasan,3.0,NaN,NaN,NaN,4.000000,2.5,5.0,4.0,5.000000,3.0
Husan,NaN,NaN,5.0,NaN,4.000000,2.0,NaN,3.0,NaN,3.0
Malika,2.0,NaN,NaN,NaN,3.000000,NaN,NaN,3.0,1.500000,3.0
Vali,NaN,5.0,1.0,3.0,NaN,5.0,1.0,NaN,NaN,3.0

In [24]:
# 5. Apply va qo‘shimcha hisoblash
# apply yordamida yangi ustun Total yarating (Price * Quantity).

df = pd.read_csv('foods.csv')

def count_total(row):
    price = row['Price']
    quantity = row['Quantity']
    total = price * quantity
    return total
df['Total'] = df.apply(count_total, axis=1)

print(df)

         Food   Category  Price  Quantity      Place  Customer  Rating   Total
0      Shorva  Fast Food  11069         1    Andijon  Gulbahor       2   11069
1         Non  Fast Food  36845         2       Xiva  Gulbahor       5   73690
2    Shashlik  Fast Food  42216         4   Toshkent     Hasan       4  168864
3    Shashlik     Milliy  48152         1   Toshkent    Malika       2   48152
4         Non   Ichimlik  42391         5   Namangan  Gulbahor       4  211955
5      Shorva   Ichimlik  15967         3   Toshkent     Hasan       5   47901
6        Qazi   Ichimlik  26865         4       Xiva     Aziza       2  107460
7         Non  Fast Food  21831         1       Xiva  Gulbahor       2   21831
8       Somsa     Milliy  21292         3  Samarqand     Husan       3   63876
9         Osh  Fast Food  20956         1  Samarqand     Hasan       2   20956
10       Qazi  Fast Food  20607         3   Farg'ona   Dilshod       5   61821
11       Qazi   Ichimlik  28505         5  Samarqand   Dilshod       3  142525
12        Non  Shirinlik  36491         3       Xiva       Ali       2  109473
13   Shashlik     Milliy  27625         5   Toshkent    Malika       2  138125
14    Lag'mon  Shirinlik  19228         2   Namangan   Dilshod       1   38456
15    Lag'mon   Ichimlik  44653         1       Xiva     Husan       5   44653
16       Qazi   Ichimlik  32019         1       Xiva       Ali       3   32019
17     Shorva   Ichimlik  42035         5   Namangan    Malika       2  210175
18        Osh  Shirinlik   8233         4     Buxoro     Husan       2   32932
19        Osh     Milliy  37442         4   Namangan      Vali       5  149768
20  Chuchvara   Ichimlik  35198         3     Buxoro      Vali       5  105594
21      Somsa  Fast Food  46657         2     Buxoro  Gulbahor       5   93314
22       Choy   Ichimlik  43044         2  Samarqand     Hasan       3   86088
23        Non   Ichimlik  46761         1     Buxoro    Malika       5   46761
24      Somsa     Milliy  18655         5   Namangan    Malika       3   93275
25       Choy     Milliy  31928         1     Buxoro    Malika       2   31928
26       Qazi  Shirinlik  25370         3  Samarqand  Gulbahor       5   76110
27        Non  Shirinlik   8936         1     Buxoro     Hasan       4    8936
28     Shorva   Ichimlik  44066         1   Farg'ona  Gulbahor       1   44066
29     Shorva     Milliy  20172         3   Toshkent  Gulbahor       2   60516
30        Non  Shirinlik  14811         5   Namangan     Husan       4   74055
31    Lag'mon   Ichimlik  26960         3   Farg'ona      Vali       1   80880
32      Manti  Shirinlik  32983         1  Samarqand     Aziza       4   32983
33      Manti  Fast Food  14603         2       Xiva      Vali       3   29206
34   Shashlik   Ichimlik  16477         5   Toshkent    Malika       5   82385
35        Non  Shirinlik  18652         4   Toshkent    Malika       1   74608
36   Shashlik  Shirinlik  49943         4   Farg'ona     Aziza       3  199772
37      Manti   Ichimlik  19089         3   Namangan  Gulbahor       2   57267
38       Qazi   Ichimlik  37581         4    Andijon  Gulbahor       3  150324
39      Manti  Fast Food  22404         5  Samarqand       Ali       1  112020
40        Osh  Fast Food  20733         4  Samarqand     Hasan       3   82932
41     Shorva   Ichimlik  38943         2     Buxoro   Dilshod       3   77886
42       Qazi     Milliy  35873         5   Farg'ona     Hasan       5  179365
43        Osh   Ichimlik  19619         4   Toshkent   Dilshod       4   78476
44     Shorva  Shirinlik  14988         3       Xiva    Malika       1   44964
45   Shashlik     Milliy  22808         3  Samarqand     Husan       3   68424
46      Somsa   Ichimlik  32205         1   Namangan   Dilshod       3   32205
47       Qazi     Milliy  17214         5     Buxoro      Vali       1   86070
48      Somsa  Shirinlik  25418         4   Namangan     Hasan       3  101672
49      Somsa  Fast Food  16773         4   Toshkent      Vali       3   67092

In [26]:
# Rating ustuniga funksiya qo‘llab, agar baho 5 bo‘lsa "Excellent", 3-4 bo‘lsa "Good", 1-2 bo‘lsa "Bad" deb yozing.

def assign_grade(Rating):
    if Rating == 5:
        return 'Excellent'
    elif Rating == 4 or Rating == 3:
        return 'Good'
    elif Rating == 1 or Rating == 2:
        return 'Bad'
    else:
        return 'Do not found'

polo['Grade'] = polo['Rating'].apply(assign_grade)
polo[['Food', 'Rating', 'Grade']]

         Food  Rating      Grade
0      Shorva       2        Bad
1         Non       5  Excellent
2    Shashlik       4       Good
3    Shashlik       2        Bad
4         Non       4       Good
5      Shorva       5  Excellent
6        Qazi       2        Bad
7         Non       2        Bad
8       Somsa       3       Good
9         Osh       2        Bad
10       Qazi       5  Excellent
11       Qazi       3       Good
12        Non       2        Bad
13   Shashlik       2        Bad
14    Lag'mon       1        Bad
15    Lag'mon       5  Excellent
16       Qazi       3       Good
17     Shorva       2        Bad
18        Osh       2        Bad
19        Osh       5  Excellent
20  Chuchvara       5  Excellent
21      Somsa       5  Excellent
22       Choy       3       Good
23        Non       5  Excellent
24      Somsa       3       Good
25       Choy       2        Bad
26       Qazi       5  Excellent
27        Non       4       Good
28     Shorva       1        Bad
29     Shorva       2        Bad
30        Non       4       Good
31    Lag'mon       1        Bad
32      Manti       4       Good
33      Manti       3       Good
34   Shashlik       5  Excellent
35        Non       1        Bad
36   Shashlik       3       Good
37      Manti       2        Bad
38       Qazi       3       Good
39      Manti       1        Bad
40        Osh       3       Good
41     Shorva       3       Good
42       Qazi       5  Excellent
43        Osh       4       Good
44     Shorva       1        Bad
45   Shashlik       3       Good
46      Somsa       3       Good
47       Qazi       1        Bad
48      Somsa       3       Good
49      Somsa       3       Good

In [32]:
# Eng ko‘p buyurtma qilingan taom nomini aniqlang.

df = pd.read_csv('foods.csv')

counts = df["Food"].value_counts()
max_orders = counts.max()
most_ordered_food = counts[counts == max_orders].index[0]
print("Eng ko‘p buyurtma qilingan taom:", most_ordered_food)

Eng ko‘p buyurtma qilingan taomlar: ['Non', 'Qazi']

In [36]:
# QOSHIMCHA +
# 6. Vaqt bo‘yicha analiz
# Date ustunini datetime tipiga o‘tkazing.

df = pd.read_csv('foods.csv')
df['Date'] = pd.date_range(start='2026-02-15', periods=len(df), freq='D')
df["Date"] = pd.to_datetime(df["Date"])
df

,Food,Category,Price,Quantity,Place,Customer,Rating,Date
0,Shorva,Fast Food,11069,1,Andijon,Gulbahor,2,2026-02-15
1,Non,Fast Food,36845,2,Xiva,Gulbahor,5,2026-02-16
2,Shashlik,Fast Food,42216,4,Toshkent,Hasan,4,2026-02-17
3,Shashlik,Milliy,48152,1,Toshkent,Malika,2,2026-02-18
4,Non,Ichimlik,42391,5,Namangan,Gulbahor,4,2026-02-19
5,Shorva,Ichimlik,15967,3,Toshkent,Hasan,5,2026-02-20
6,Qazi,Ichimlik,26865,4,Xiva,Aziza,2,2026-02-21
7,Non,Fast Food,21831,1,Xiva,Gulbahor,2,2026-02-22
8,Somsa,Milliy,21292,3,Samarqand,Husan,3,2026-02-23
9,Osh,Fast Food,20956,1,Samarqand,Hasan,2,2026-02-24
10,Qazi,Fast Food,20607,3,Farg'ona,Dilshod,5,2026-02-25
11,Qazi,Ichimlik,28505,5,Samarqand,Dilshod,3,2026-02-26
12,Non,Shirinlik,36491,3,Xiva,Ali,2,2026-02-27
13,Shashlik,Milliy,27625,5,Toshkent,Malika,2,2026-02-28
14,Lag'mon,Shirinlik,19228,2,Namangan,Dilshod,1,2026-03-01
15,Lag'mon,Ichimlik,44653,1,Xiva,Husan,5,2026-03-02
16,Qazi,Ichimlik,32019,1,Xiva,Ali,3,2026-03-03
17,Shorva,Ichimlik,42035,5,Namangan,Malika,2,2026-03-04
18,Osh,Shirinlik,8233,4,Buxoro,Husan,2,2026-03-05
19,Osh,Milliy,37442,4,Namangan,Vali,5,2026-03-06
20,Chuchvara,Ichimlik,35198,3,Buxoro,Vali,5,2026-03-07
21,Somsa,Fast Food,46657,2,Buxoro,Gulbahor,5,2026-03-08
22,Choy,Ichimlik,43044,2,Samarqand,Hasan,3,2026-03-09
23,Non,Ichimlik,46761,1,Buxoro,Malika,5,2026-03-10
24,Somsa,Milliy,18655,5,Namangan,Malika,3,2026-03-11
25,Choy,Milliy,31928,1,Buxoro,Malika,2,2026-03-12
26,Qazi,Shirinlik,25370,3,Samarqand,Gulbahor,5,2026-03-13
27,Non,Shirinlik,8936,1,Buxoro,Hasan,4,2026-03-14
28,Shorva,Ichimlik,44066,1,Farg'ona,Gulbahor,1,2026-03-15
29,Shorva,Milliy,20172,3,Toshkent,Gulbahor,2,2026-03-16
30,Non,Shirinlik,14811,5,Namangan,Husan,4,2026-03-17
31,Lag'mon,Ichimlik,26960,3,Farg'ona,Vali,1,2026-03-18
32,Manti,Shirinlik,32983,1,Samarqand,Aziza,4,2026-03-19
33,Manti,Fast Food,14603,2,Xiva,Vali,3,2026-03-20
34,Shashlik,Ichimlik,16477,5,Toshkent,Malika,5,2026-03-21
35,Non,Shirinlik,18652,4,Toshkent,Malika,1,2026-03-22
36,Shashlik,Shirinlik,49943,4,Farg'ona,Aziza,3,2026-03-23
37,Manti,Ichimlik,19089,3,Namangan,Gulbahor,2,2026-03-24
38,Qazi,Ichimlik,37581,4,Andijon,Gulbahor,3,2026-03-25
39,Manti,Fast Food,22404,5,Samarqand,Ali,1,2026-03-26
40,Osh,Fast Food,20733,4,Samarqand,Hasan,3,2026-03-27
41,Shorva,Ichimlik,38943,2,Buxoro,Dilshod,3,2026-03-28
42,Qazi,Milliy,35873,5,Farg'ona,Hasan,5,2026-03-29
43,Osh,Ichimlik,19619,4,Toshkent,Dilshod,4,2026-03-30
44,Shorva,Shirinlik,14988,3,Xiva,Malika,1,2026-03-31
45,Shashlik,Milliy,22808,3,Samarqand,Husan,3,2026-04-01
46,Somsa,Ichimlik,32205,1,Namangan,Dilshod,3,2026-04-02
47,Qazi,Milliy,17214,5,Buxoro,Vali,1,2026-04-03
48,Somsa,Shirinlik,25418,4,Namangan,Hasan,3,2026-04-04
49,Somsa,Fast Food,16773,4,Toshkent,Vali,3,2026-04-05

In [42]:
# Oxirgi 7 kunda berilgan buyurtmalar sonini hisoblang.

df = pd.read_csv('foods.csv')

df['Date'] = pd.date_range(start='2026-02-15', periods=len(df), freq='D')
df["Date"] = pd.to_datetime(df["Date"])
today = pd.to_datetime('today')
seven_days_ago = today - pd.Timedelta(days=7)
last_week_orders = df[df['Date'] >= seven_days_ago]
num_orders = len(last_week_orders)

print(f'Oxirgi 7 kunda berilgan buyurtmalar soni: {num_orders}')
print("Buyurtmalar ro'yxati:")
print(last_week_orders[['Food', 'Date']])

Oxirgi 7 kunda berilgan buyurtmalar soni: 30
Buyurtmalar ro'yxati:
         Food       Date
20  Chuchvara 2026-03-07
21      Somsa 2026-03-08
22       Choy 2026-03-09
23        Non 2026-03-10
24      Somsa 2026-03-11
25       Choy 2026-03-12
26       Qazi 2026-03-13
27        Non 2026-03-14
28     Shorva 2026-03-15
29     Shorva 2026-03-16
30        Non 2026-03-17
31    Lag'mon 2026-03-18
32      Manti 2026-03-19
33      Manti 2026-03-20
34   Shashlik 2026-03-21
35        Non 2026-03-22
36   Shashlik 2026-03-23
37      Manti 2026-03-24
38       Qazi 2026-03-25
39      Manti 2026-03-26
40        Osh 2026-03-27
41     Shorva 2026-03-28
42       Qazi 2026-03-29
43        Osh 2026-03-30
44     Shorva 2026-03-31
45   Shashlik 2026-04-01
46      Somsa 2026-04-02
47       Qazi 2026-04-03
48      Somsa 2026-04-04
49      Somsa 2026-04-05

In [50]:
# Har bir oy bo‘yicha jami tushumni (Price * Quantity) toping.

df = pd.read_csv('foods.csv')

df['Date'] = pd.date_range(start='2026-02-15', periods=len(df), freq='D')
df['Date'] = pd.to_datetime(df['Date'])
df['Total'] = df['Price'] * df['Quantity']
df['Month'] = df['Date'].dt.to_period('M')
monthly_income = df.groupby('Month')['Total'].sum()

print(monthly_income)

Month
2026-02    1227698
2026-03    2511714
2026-04     355463
Freq: M, Name: Total, dtype: int64

In [ ]:
# 7. GroupBy + Apply
# Har bir Customer uchun o‘rtacha chek summasini hisoblang.

df = pd.read_csv('foods.csv')
df['Total'] = df['Price'] * df['Quantity']

def customer_summary(group):
    avg_total = group['Total'].mean()
    group = group.copy()
    group['Avg_Check'] = avg_total
    return group[['Food', 'Price', 'Quantity', 'Total', 'Avg_Check']]
result = df.groupby('Customer').apply(customer_summary)

result = df.groupby('Customer', group_keys=False).apply(customer_summary)

print(result)

In [12]:
# apply yordamida eng ko‘p buyurtma qilgan mijozni aniqlang.

df = pd.read_csv('foods.csv')


counts = df["Customer"].value_counts()
max_customers = counts.max()
most_ordered_customer = counts[counts == max_customers].index[0]
print("Eng ko‘p buyurtma qiligan mijoz:", most_ordered_customer)

Eng ko‘p buyurtma qiligan mijoz: Gulbahor

In [26]:
# Place bo‘yicha eng qimmat buyurtmani toping.

df = pd.read_csv('foods.csv')

result = df.loc[[df['Price'].idxmax()]]
print(result[['Food','Price','Place']])

        Food  Price     Place
36  Shashlik  49943  Farg'ona

In [28]:
# 8. Pivot_table + MultiIndex
# Place va Category bo‘yicha pivot_table tuzing, unda Pricening o‘rtacha va Quantity yig‘indisi chiqsin.

pivot = pd.pivot_table(polo, values =['Price','Quantity'], index = 'Place', columns = 'Category', aggfunc = {'Price': 'mean', 'Quantity': 'sum'})
pivot

                  Price                                   Quantity           \
Category      Fast Food      Ichimlik   Milliy Shirinlik Fast Food Ichimlik
Place
Andijon    11069.000000  37581.000000      NaN       NaN       1.0      4.0
Buxoro     46657.000000  40300.666667  24571.0    8584.5       2.0      6.0
Farg'ona   20607.000000  35513.000000  35873.0   49943.0       3.0      4.0
Namangan            NaN  33930.000000  28048.5   19819.0       NaN     14.0
Samarqand  21364.333333  35774.500000  22050.0   29176.5      10.0      7.0
Toshkent   29494.500000  17354.333333  31983.0   18652.0       8.0     12.0
Xiva       24426.333333  34512.333333      NaN   25739.5       5.0      6.0


Category  Milliy Shirinlik
Place
Andijon      NaN       NaN
Buxoro       6.0       5.0
Farg'ona     5.0       4.0
Namangan     9.0      11.0
Samarqand    6.0       4.0
Toshkent     9.0       4.0
Xiva         NaN       6.0

In [29]:
# Customer va Food kesimida Rating bo‘yicha o‘rtacha baho chiqaring.

pivot = pd.pivot_table(polo, values='Rating', index='Customer', columns='Food', aggfunc='mean')
pivot

Food,Choy,Chuchvara,Lag'mon,Manti,Non,Osh,Qazi,Shashlik,Shorva,Somsa
Customer,,,,,,,,,,
Ali,NaN,NaN,NaN,1.0,2.000000,NaN,3.0,NaN,NaN,NaN
Aziza,NaN,NaN,NaN,4.0,NaN,NaN,2.0,3.0,NaN,NaN
Dilshod,NaN,NaN,1.0,NaN,NaN,4.0,4.0,NaN,3.000000,3.0
Gulbahor,NaN,NaN,NaN,2.0,3.666667,NaN,4.0,NaN,1.666667,5.0
Hasan,3.0,NaN,NaN,NaN,4.000000,2.5,5.0,4.0,5.000000,3.0
Husan,NaN,NaN,5.0,NaN,4.000000,2.0,NaN,3.0,NaN,3.0
Malika,2.0,NaN,NaN,NaN,3.000000,NaN,NaN,3.0,1.500000,3.0
Vali,NaN,5.0,1.0,3.0,NaN,5.0,1.0,NaN,NaN,3.0

In [34]:
# 9. Filter + Sorting
# Rating < 3 bo‘lgan buyurtmalarni saralab chiqaring.


df = pd.read_csv('foods.csv')

filtered = df[df['Rating'] < 3]
result = filtered.sort_values(by='Rating')
print(result)

        Food   Category  Price  Quantity      Place  Customer  Rating
0     Shorva  Fast Food  11069         1    Andijon  Gulbahor       2
3   Shashlik     Milliy  48152         1   Toshkent    Malika       2
6       Qazi   Ichimlik  26865         4       Xiva     Aziza       2
7        Non  Fast Food  21831         1       Xiva  Gulbahor       2
9        Osh  Fast Food  20956         1  Samarqand     Hasan       2
12       Non  Shirinlik  36491         3       Xiva       Ali       2
13  Shashlik     Milliy  27625         5   Toshkent    Malika       2
14   Lag'mon  Shirinlik  19228         2   Namangan   Dilshod       1
17    Shorva   Ichimlik  42035         5   Namangan    Malika       2
18       Osh  Shirinlik   8233         4     Buxoro     Husan       2
25      Choy     Milliy  31928         1     Buxoro    Malika       2
28    Shorva   Ichimlik  44066         1   Farg'ona  Gulbahor       1
29    Shorva     Milliy  20172         3   Toshkent  Gulbahor       2
31   Lag'mon   Ichimlik  26960         3   Farg'ona      Vali       1
35       Non  Shirinlik  18652         4   Toshkent    Malika       1
37     Manti   Ichimlik  19089         3   Namangan  Gulbahor       2
39     Manti  Fast Food  22404         5  Samarqand       Ali       1
44    Shorva  Shirinlik  14988         3       Xiva    Malika       1
47      Qazi     Milliy  17214         5     Buxoro      Vali       1

In [37]:
# Narxi bo‘yicha eng qimmat 5 ta buyurtmani toping.

df = pd.read_csv('foods.csv')

top5 = df.sort_values(by='Price', ascending=False).head(5)
print(top5[['Food', 'Price']])

        Food  Price
36  Shashlik  49943
3   Shashlik  48152
23       Non  46761
21     Somsa  46657
15   Lag'mon  44653

In [45]:
# Quantity >= 5 bo‘lgan buyurtmalardan jami tushumni hisoblang.

df = pd.read_csv('foods.csv')

filtered = df.loc[df['Quantity'] >= 5].copy()
filtered.loc[:, 'Revenue'] = filtered['Price'] * filtered['Quantity']
total_revenue = sum(filtered['Revenue'])

print('Quantity >= 5 bo‘lgan buyurtmalardan jami tushum:', total_revenue)

Quantity >= 5 bo‘lgan buyurtmalardan jami tushum: 1329950

In [48]:
# 10. Qo‘shimcha hisoblash
# Yangi ustun Total yarating (Price * Quantity).

df = pd.read_csv('foods.csv')

df['Total'] = df['Price'] * df['Quantity']
df

         Food   Category  Price  Quantity      Place  Customer  Rating   Total
0      Shorva  Fast Food  11069         1    Andijon  Gulbahor       2   11069
1         Non  Fast Food  36845         2       Xiva  Gulbahor       5   73690
2    Shashlik  Fast Food  42216         4   Toshkent     Hasan       4  168864
3    Shashlik     Milliy  48152         1   Toshkent    Malika       2   48152
4         Non   Ichimlik  42391         5   Namangan  Gulbahor       4  211955
5      Shorva   Ichimlik  15967         3   Toshkent     Hasan       5   47901
6        Qazi   Ichimlik  26865         4       Xiva     Aziza       2  107460
7         Non  Fast Food  21831         1       Xiva  Gulbahor       2   21831
8       Somsa     Milliy  21292         3  Samarqand     Husan       3   63876
9         Osh  Fast Food  20956         1  Samarqand     Hasan       2   20956
10       Qazi  Fast Food  20607         3   Farg'ona   Dilshod       5   61821
11       Qazi   Ichimlik  28505         5  Samarqand   Dilshod       3  142525
12        Non  Shirinlik  36491         3       Xiva       Ali       2  109473
13   Shashlik     Milliy  27625         5   Toshkent    Malika       2  138125
14    Lag'mon  Shirinlik  19228         2   Namangan   Dilshod       1   38456
15    Lag'mon   Ichimlik  44653         1       Xiva     Husan       5   44653
16       Qazi   Ichimlik  32019         1       Xiva       Ali       3   32019
17     Shorva   Ichimlik  42035         5   Namangan    Malika       2  210175
18        Osh  Shirinlik   8233         4     Buxoro     Husan       2   32932
19        Osh     Milliy  37442         4   Namangan      Vali       5  149768
20  Chuchvara   Ichimlik  35198         3     Buxoro      Vali       5  105594
21      Somsa  Fast Food  46657         2     Buxoro  Gulbahor       5   93314
22       Choy   Ichimlik  43044         2  Samarqand     Hasan       3   86088
23        Non   Ichimlik  46761         1     Buxoro    Malika       5   46761
24      Somsa     Milliy  18655         5   Namangan    Malika       3   93275
25       Choy     Milliy  31928         1     Buxoro    Malika       2   31928
26       Qazi  Shirinlik  25370         3  Samarqand  Gulbahor       5   76110
27        Non  Shirinlik   8936         1     Buxoro     Hasan       4    8936
28     Shorva   Ichimlik  44066         1   Farg'ona  Gulbahor       1   44066
29     Shorva     Milliy  20172         3   Toshkent  Gulbahor       2   60516
30        Non  Shirinlik  14811         5   Namangan     Husan       4   74055
31    Lag'mon   Ichimlik  26960         3   Farg'ona      Vali       1   80880
32      Manti  Shirinlik  32983         1  Samarqand     Aziza       4   32983
33      Manti  Fast Food  14603         2       Xiva      Vali       3   29206
34   Shashlik   Ichimlik  16477         5   Toshkent    Malika       5   82385
35        Non  Shirinlik  18652         4   Toshkent    Malika       1   74608
36   Shashlik  Shirinlik  49943         4   Farg'ona     Aziza       3  199772
37      Manti   Ichimlik  19089         3   Namangan  Gulbahor       2   57267
38       Qazi   Ichimlik  37581         4    Andijon  Gulbahor       3  150324
39      Manti  Fast Food  22404         5  Samarqand       Ali       1  112020
40        Osh  Fast Food  20733         4  Samarqand     Hasan       3   82932
41     Shorva   Ichimlik  38943         2     Buxoro   Dilshod       3   77886
42       Qazi     Milliy  35873         5   Farg'ona     Hasan       5  179365
43        Osh   Ichimlik  19619         4   Toshkent   Dilshod       4   78476
44     Shorva  Shirinlik  14988         3       Xiva    Malika       1   44964
45   Shashlik     Milliy  22808         3  Samarqand     Husan       3   68424
46      Somsa   Ichimlik  32205         1   Namangan   Dilshod       3   32205
47       Qazi     Milliy  17214         5     Buxoro      Vali       1   86070
48      Somsa  Shirinlik  25418         4   Namangan     Hasan       3  101672
49      Somsa  Fast Food  16773         4   Toshkent      Vali       3   67092

In [53]:
# Customer bo‘yicha jami Totalni hisoblang va eng ko‘p pul sarflagan mijozni aniqlang.

df = pd.read_csv('foods.csv')


df['Total'] = df['Price'] * df['Quantity']
customer_total = df.groupby('Customer')['Total'].sum()
top_customer = customer_total.idxmax()
top_amount = customer_total.max()

print("Eng ko‘p pul sarflagan mijoz:", top_customer, '\n', 'Umumiy sarfi:', top_amount)

Eng ko‘p pul sarflagan mijoz: Gulbahor
 umumiy sarfi: 800142

In [54]:
# Sana bo‘yicha rolling(7) yordamida haftalik tushumni ko‘rsating.

df = pd.read_csv('foods.csv')

df['Date'] = pd.date_range(start='2026-03-01', periods=len(df), freq='D')
df['Total'] = df['Price'] * df['Quantity']
df = df.sort_values('Date')
df['Weekly_Revenue'] = df['Total'].rolling(7).sum()

print(df[['Date','Total','Weekly_Revenue']])

         Date   Total  Weekly_Revenue
0  2026-03-01   11069             NaN
1  2026-03-02   73690             NaN
2  2026-03-03  168864             NaN
3  2026-03-04   48152             NaN
4  2026-03-05  211955             NaN
5  2026-03-06   47901             NaN
6  2026-03-07  107460        669091.0
7  2026-03-08   21831        679853.0
8  2026-03-09   63876        670039.0
9  2026-03-10   20956        522131.0
10 2026-03-11   61821        535800.0
11 2026-03-12  142525        466370.0
12 2026-03-13  109473        527942.0
13 2026-03-14  138125        558607.0
14 2026-03-15   38456        575232.0
15 2026-03-16   44653        556009.0
16 2026-03-17   32019        567072.0
17 2026-03-18  210175        715426.0
18 2026-03-19   32932        605833.0
19 2026-03-20  149768        646128.0
20 2026-03-21  105594        613597.0
21 2026-03-22   93314        668455.0
22 2026-03-23   86088        709890.0
23 2026-03-24   46761        724632.0
24 2026-03-25   93275        607732.0
25 2026-03-26   31928        606728.0
26 2026-03-27   76110        533070.0
27 2026-03-28    8936        436412.0
28 2026-03-29   44066        387164.0
29 2026-03-30   60516        361592.0
30 2026-03-31   74055        388886.0
31 2026-04-01   80880        376491.0
32 2026-04-02   32983        377546.0
33 2026-04-03   29206        330642.0
34 2026-04-04   82385        404091.0
35 2026-04-05   74608        434633.0
36 2026-04-06  199772        573889.0
37 2026-04-07   57267        557101.0
38 2026-04-08  150324        626545.0
39 2026-04-09  112020        705582.0
40 2026-04-10   82932        759308.0
41 2026-04-11   77886        754809.0
42 2026-04-12  179365        859566.0
43 2026-04-13   78476        738270.0
44 2026-04-14   44964        725967.0
45 2026-04-15   68424        644067.0
46 2026-04-16   32205        564252.0
47 2026-04-17   86070        567390.0
48 2026-04-18  101672        591176.0
49 2026-04-19   67092        478903.0