In [2]:

import pandas as pd
from pandas.core.common import fill_missing_names

hr = pd.read_excel('HR_Dataset_for_PowerBI_with_Errors.xlsx')
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [3]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\pc-5\appdata\local\programs\python\python310\lib\site-packages (2.3.2)
Requirement already satisfied: openpyxl in c:\users\pc-5\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.22.4 in c:\users\pc-5\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc-5\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc-5\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc-5\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\pc-5\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\pc-5\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
hr.isnull().sum()

Employee ID         6
Department          6
Hire Date           5
Current Position    7
Salary (USD)        1
Last Raise Date     7
Position Changed    6
New Position        6
dtype: int64

In [13]:
hr.loc[0: 99, 'Employee ID'] = ['E' +  str(i).zfill(4)
                                for i in range(1, len(hr) + 1)]
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [14]:
hr.isnull().sum()

Employee ID         0
Department          0
Hire Date           0
Current Position    0
Salary (USD)        0
Last Raise Date     0
Position Changed    6
New Position        6
dtype: int64

In [8]:
hr['Department'] = hr['Department'].fillna('Data Analyst')
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [9]:
hr['Hire Date'] = hr['Hire Date'].interpolate(method='linear')
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [10]:
hr.loc[[14, 23, 28, 40, 66, 79, 81], 'Current Position'] = ['Mid', 'Manager', 'Junior', 'Lead', 'Junior', 'Mid', 'Senior']
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [11]:
hr.loc[83,'Salary (USD)'] = 2000

hr.loc[hr['Salary (USD)'] < 0, 'Salary (USD)'] = hr['Salary (USD)'].abs()
hr.loc[hr['Salary (USD)'] < 11, 'Salary (USD)'] = hr.loc[hr['Salary (USD)'] < 11, 'Salary (USD)'] * 100

hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [12]:
hr['Last Raise Date'] = hr['Last Raise Date'].interpolate(method='linear')
hr

,Employee ID,Department,Hire Date,Current Position,Salary (USD),Last Raise Date,Position Changed,New Position
0,E0001,HR,2017-10-11,Senior,1530.0,2020-01-29,No,Senior
1,E0002,IT,2018-10-04,Junior,570.0,2020-01-31,Yes,Lead
2,E0003,IT,2019-12-24,Senior,1400.0,2020-08-07,No,Senior
3,E0004,Sales,2021-07-12,Junior,760.0,2023-09-06,Yes,Lead
4,E0005,Marketing,2021-07-31,Lead,800.0,2022-11-10,No,Lead
...,...,...,...,...,...,...,...,...
95,E0096,Finance,2021-08-11,Lead,1760.0,2024-03-06,Yes,Manager
96,E0097,IT,2020-03-13,Manager,1880.0,2021-02-15,No,Manager
97,E0098,IT,2016-11-20,Senior,1450.0,2018-03-29,No,Senior
98,E0099,Logistics,2016-02-08,Mid,2070.0,2018-11-09,No,Mid
99,E0100,Marketing,2016-01-21,Lead,880.0,2018-09-27,No,Lead

In [ ]:
hr.loc[[23, 33, 44], 'Current Position'] = ['Manager', 'Lead', 'Senior' 'Junior', 'Mid', 'Senior']
hr